repos:
  # General hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: mixed-line-ending
      - id: check-added-large-files

  # Terraform-specific hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args: ["--hook-config=--retry-once-with-cleanup=true"]
      # Enable these once you add config:
      # - id: terraform_tflint
      #   args:
      #     - "--args=--init"
      #     - "--args=--config=./.tflint.hcl"
      # - id: terraform_docs
      #   args:
      #     - "--hook-config=--create-file-if-not-exist=true"
      #     - "--hook-config=--path-to-file=README.md"
      #     - "--hook-config=--add-to-existing-file=true"
      #     - "--args=--hide provider,modules,requirements"

  # YAML/Markdown linting (optional)
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ["--disable", "MD013"]  # ignore long lines; tweak as needed
