version: "3.8"

services:
  kind-registry:
    image: registry:2
    container_name: kind-registry
    ports:
      - "5000:5000"
    restart: always

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: changeme123
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    restart: always
 
  consul:
    image: hashicorp/consul
    container_name: consul
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0
    restart: always
 

volumes:
  minio-data:
